# Image Stitching

In [2]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import cv2

print("NumPy version:", np.__version__)
print("Matplotlib version:", matplotlib.__version__)
print("OpenCV version:", cv2.__version__)

NumPy version: 1.26.4
Matplotlib version: 3.8.0
OpenCV version: 4.9.0


In [3]:
images = [cv2.imread(f'../database/image_stitching/ic{i}.jpg') for i in range(1, 5)]
print(images[0])

[[[212 149  98]
  [214 151 100]
  [215 152 101]
  ...
  [ 28  26  16]
  [ 29  27  17]
  [ 30  28  18]]

 [[217 154 103]
  [213 150  99]
  [214 151 100]
  ...
  [ 27  25  15]
  [ 28  26  16]
  [ 29  27  17]]

 [[219 156 105]
  [216 153 102]
  [216 153 102]
  ...
  [ 30  28  18]
  [ 30  28  18]
  [ 30  28  18]]

 ...

 [[ 31  71  70]
  [ 31  71  70]
  [ 32  71  73]
  ...
  [ 96 100 101]
  [ 97  99 100]
  [ 97  99 100]]

 [[ 30  69  71]
  [ 29  68  70]
  [ 30  69  71]
  ...
  [ 93  96 100]
  [ 94  98  99]
  [ 96 100 101]]

 [[ 31  70  72]
  [ 30  69  71]
  [ 31  70  72]
  ...
  [ 90  93  97]
  [ 93  97  98]
  [ 96 100 101]]]


In [4]:
stitcher = cv2.Stitcher_create()

status, stitched_image = stitcher.stitch(images)

if status == cv2.Stitcher_OK:
    cv2.imwrite('../database/image_stitching/ic_panorama.png', stitched_image)
    print("Panorama created successfully and saved as ic.png")
else:
    print(f"Image stitching failed with status {status}")

Panorama created successfully and saved as ic.png


In [5]:
# result = cv2.imread('../database/image_stitching/ic_panorama.png')

# image_rgb = cv2.cvtColor(result, cv2.COLOR_BGR2RGB)

# plt.imshow(image_rgb)
# plt.axis('off')
# plt.show()